name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["root"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ChongxiSama
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss
          plugin_languages_details: percentage, lines
          plugin_languages_limit: 10
          plugin_languages_recent_load: 500
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: no
          plugin_lines: yes
          plugin_lines_sections: repositories
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          filename: github-metrics.svg
          config_order: base.header, languages, habits, lines, achievements
          committer_token: ${{ secrets.GITHUB_TOKEN }}
